HEIGHT = 920
WIDTH = 1230
TILE_SIZE_X = WIDTH  // 41
TILE_SIZE_Y = (HEIGHT - 50)// 29
STARTING_POSITION_X = WIDTH - (TILE_SIZE_X * 20) - 15
STARTING_POSITION_Y = HEIGHT - 7 * TILE_SIZE_Y  - 4

UP = (0, -1)
DOWN = (0, 1)
LEFT = (-1, 0)
RIGHT = (1, 0)
DIRECTIONS = [RIGHT, LEFT, UP, DOWN]

FRIGHTENED_SPEED = 0.5
EATEN_SPEED = 5
PINKY_SPEED = 1
